version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/brevity-engine/hoppscotch"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]